// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyWebAppMVC.DBOperations;

#nullable disable

namespace MyWebAppMVC.Migrations
{
    [DbContext(typeof(WarehouseDBContext))]
    [Migration("20241126111123_AddWarehouseDB")]
    partial class AddWarehouseDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyWebAppMVC.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Winsor & Newton",
                            Price = 1m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Faber Castell",
                            Price = 10m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 3,
                            Name = "Premier",
                            Price = 1m,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("MyWebAppMVC.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("supplier");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactNo = "0872662523",
                            Email = "evansart@gmail.com",
                            Name = "Evans Art"
                        },
                        new
                        {
                            Id = 2,
                            ContactNo = "0861273743",
                            Email = "fine.art@gmail.com",
                            Name = "Fine Art"
                        },
                        new
                        {
                            Id = 3,
                            ContactNo = "0834567351",
                            Email = "still.art@hotmail.com",
                            Name = "Still Art"
                        });
                });

            modelBuilder.Entity("MyWebAppMVC.Models.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("warehouse");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123, Downing Street, Dublin",
                            ContactNo = "0872734567",
                            Location = "Ireland",
                            Name = "Warehouse1"
                        },
                        new
                        {
                            Id = 2,
                            Address = "375, Beauvelgrade Street, Paris",
                            ContactNo = "0834562874",
                            Location = "France",
                            Name = "Warehouse2"
                        },
                        new
                        {
                            Id = 3,
                            Address = "421, Unter den Linden, Berlin",
                            ContactNo = "0865748902",
                            Location = "Germany",
                            Name = "Warehouse3"
                        });
                });

            modelBuilder.Entity("ProductSupplier", b =>
                {
                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.Property<int>("SuppliersId")
                        .HasColumnType("int");

                    b.HasKey("ProductsId", "SuppliersId");

                    b.HasIndex("SuppliersId");

                    b.ToTable("ProductSupplier");
                });

            modelBuilder.Entity("MyWebAppMVC.Models.Product", b =>
                {
                    b.HasOne("MyWebAppMVC.Models.Warehouse", null)
                        .WithMany("Products")
                        .HasForeignKey("WarehouseId");
                });

            modelBuilder.Entity("ProductSupplier", b =>
                {
                    b.HasOne("MyWebAppMVC.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyWebAppMVC.Models.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SuppliersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyWebAppMVC.Models.Warehouse", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
